# Mapeamento Bandit Test IDs para CWE (Common Weakness Enumeration)
bandit_cwe_mapping:
  # Injection vulnerabilities
  B101: "CWE-78"   # assert_used - Debug statements in production
  B102: "CWE-78"   # exec_used - Code injection via exec()
  B103: "CWE-78"   # set_bad_file_permissions - Insecure file permissions
  B104: "CWE-78"   # hardcoded_bind_all_interfaces - Binding to all interfaces
  B105: "CWE-798"  # hardcoded_password_string - Hard-coded credentials
  B106: "CWE-798"  # hardcoded_password_funcarg - Hard-coded password in function argument
  B107: "CWE-798"  # hardcoded_password_default - Hard-coded password in default argument
  B108: "CWE-377"  # hardcoded_tmp_directory - Insecure temporary file
  B110: "CWE-703"  # try_except_pass - Exception handling issues
  B112: "CWE-703"  # try_except_continue - Exception handling issues
  B113: "CWE-400"  # request-without-timeout - Uncontrolled Resource Consumption
  
  # Cryptographic issues
  B301: "CWE-502"  # blacklist_calls - pickle usage (deserialization)
  B302: "CWE-327"  # blacklist_calls - Deprecated crypto functions
  B303: "CWE-327"  # blacklist_calls - MD5 hash usage
  B304: "CWE-327"  # blacklist_calls - Insecure cipher usage
  B305: "CWE-327"  # blacklist_calls - Insecure cipher mode
  B306: "CWE-327"  # blacklist_calls - mktemp usage
  B307: "CWE-78"   # blacklist_calls - eval usage
  B308: "CWE-20"   # blacklist_calls - mark_safe usage
  B309: "CWE-327"  # blacklist_calls - httpsconnection usage
  B310: "CWE-330"  # blacklist_calls - urllib_urlopen usage
  B311: "CWE-330"  # blacklist_calls - random usage for crypto
  B312: "CWE-209"  # blacklist_calls - telnetlib usage
  B313: "CWE-611"  # blacklist_calls - xml usage
  B314: "CWE-611"  # blacklist_calls - xml usage
  B315: "CWE-611"  # blacklist_calls - xml usage
  B316: "CWE-611"  # blacklist_calls - xml usage
  B317: "CWE-611"  # blacklist_calls - xml usage
  B318: "CWE-611"  # blacklist_calls - xml usage
  B319: "CWE-611"  # blacklist_calls - xml usage
  B320: "CWE-611"  # blacklist_calls - xml usage
  B321: "CWE-377"  # blacklist_calls - ftplib usage
  B322: "CWE-20"   # blacklist_calls - input usage
  B323: "CWE-327"  # blacklist_calls - unverified_context
  B324: "CWE-327"  # hashlib_new_insecure_functions
  B325: "CWE-377"  # tempfile usage
  
  # Injection and command execution
  B401: "CWE-319"  # blacklist_imports - telnetlib import (cleartext protocol)
  B402: "CWE-377"  # blacklist_imports - ftplib import
  B403: "CWE-502"  # blacklist_imports - pickle import (deserialization)
  B404: "CWE-78"   # blacklist_imports - subprocess import
  B405: "CWE-611"  # blacklist_imports - xml imports
  B406: "CWE-611"  # blacklist_imports - xml imports
  B407: "CWE-611"  # blacklist_imports - xml imports
  B408: "CWE-611"  # blacklist_imports - xml imports
  B409: "CWE-611"  # blacklist_imports - xml imports
  B410: "CWE-611"  # blacklist_imports - xml imports
  B411: "CWE-330"  # blacklist_imports - random import
  B412: "CWE-209"  # blacklist_imports - logging import issues
  B413: "CWE-20"   # blacklist_imports - pycrypto import
  B610: "CWE-20"   # django_extra_used - Django extra() SQL injection
  B613: "CWE-176"  # suspicious-unicode - Bidirectional Unicode
  B318: "CWE-611"  # xml usage
  B319: "CWE-611"  # xml usage
  
  # Web and network security
  B501: "CWE-295"  # request_with_no_cert_validation
  B502: "CWE-326"  # ssl_with_bad_version - Weak SSL/TLS versions
  B503: "CWE-326"  # ssl_with_bad_defaults - Insecure SSL defaults  
  B504: "CWE-326"  # ssl_with_no_version - No SSL version specified
  B505: "CWE-326"  # weak_cryptographic_key - Weak crypto key
  B506: "CWE-502"  # yaml_load - Deserialization of untrusted data
  B507: "CWE-295"  # ssh_no_host_key_verification
  B508: "CWE-319"  # snmp_insecure_version
  B509: "CWE-319"  # snmp_weak_cryptography
  
  # Injection vulnerabilities
  B601: "CWE-78"   # paramiko_calls - Shell injection via paramiko
  B602: "CWE-78"   # subprocess_popen_with_shell_equals_true
  B603: "CWE-78"   # subprocess_without_shell_equals_true
  B604: "CWE-78"   # any_other_function_with_shell_equals_true
  B605: "CWE-78"   # start_process_with_a_shell
  B606: "CWE-78"   # start_process_with_no_shell
  B607: "CWE-78"   # start_process_with_partial_path
  B608: "CWE-89"   # hardcoded_sql_expressions
  B609: "CWE-78"   # linux_commands_wildcard_injection
  B610: "CWE-20"   # django_extra_used
  B611: "CWE-20"   # django_rawsql_used
  B612: "CWE-209"  # logging_config_insecure_listen
  B613: "CWE-176"  # suspicious_unicode - Bidirectional Unicode
  B701: "CWE-79"   # jinja2_autoescape_false - XSS via template injection
  B702: "CWE-79"   # use_of_mako_templates - Template injection
  B703: "CWE-79"   # django_mark_safe - XSS via mark_safe

# Additional Bandit mappings for comprehensive coverage
additional_mappings:
  # Flask/Django specific  
  B201: "CWE-489"  # flask_debug_true - Active debug code in production
  B202: "CWE-22"   # tarfile_unsafe_members - Path traversal
  
  # Additional missing mappings based on Bandit documentation
  B109: "CWE-798"  # password_config_option_not_marked_secret
  B801: "CWE-327"  # blacklist_calls - Insecure hash functions
  B901: "CWE-78"   # exec_used - Code injection
  B902: "CWE-78"   # exec_used - Code injection  
  B903: "CWE-78"   # exec_used - Code injection

# CWE descriptions for reference (expanded with OWASP Top 10 and more)
cwe_descriptions:
  # OWASP Top 10 2021 related CWEs
  "CWE-20": "Improper Input Validation (OWASP A03:2021)"
  "CWE-78": "OS Command Injection (OWASP A03:2021)"
  "CWE-79": "Cross-site Scripting (OWASP A03:2021)"
  "CWE-89": "SQL Injection (OWASP A03:2021)"
  "CWE-94": "Code Injection (OWASP A03:2021)"
  "CWE-200": "Information Exposure (OWASP A01:2021)"
  "CWE-209": "Information Exposure Through Error Messages"
  "CWE-269": "Improper Privilege Management (OWASP A01:2021)"
  "CWE-276": "Incorrect Default Permissions (OWASP A05:2021)"
  "CWE-287": "Improper Authentication (OWASP A07:2021)"
  "CWE-295": "Improper Certificate Validation (OWASP A02:2021)"
  "CWE-319": "Cleartext Transmission (OWASP A02:2021)"
  "CWE-326": "Inadequate Encryption Strength (OWASP A02:2021)"
  "CWE-327": "Broken/Risky Cryptographic Algorithm (OWASP A02:2021)"
  "CWE-330": "Use of Insufficiently Random Values (OWASP A02:2021)"
  "CWE-352": "Cross-Site Request Forgery (OWASP A01:2021)"
  "CWE-377": "Insecure Temporary File"
  "CWE-502": "Deserialization of Untrusted Data (OWASP A08:2021)"
  "CWE-522": "Insufficiently Protected Credentials (OWASP A07:2021)"
  "CWE-611": "XML External Entity Reference (OWASP A05:2021)"
  "CWE-614": "Sensitive Cookie Without Secure Flag (OWASP A05:2021)"
  "CWE-703": "Improper Check/Handling of Exceptional Conditions"
  "CWE-732": "Incorrect Permission Assignment (OWASP A05:2021)"
  "CWE-798": "Hard-coded Credentials (OWASP A07:2021)"
  "CWE-829": "Inclusion of Functionality from Untrusted Control Sphere"
  "CWE-918": "Server-Side Request Forgery (OWASP A10:2021)"
  
  # Additional security-relevant CWEs
  "CWE-22": "Path Traversal (OWASP A01:2021)"
  "CWE-113": "HTTP Response Splitting"
  "CWE-116": "Improper Encoding or Escaping of Output"
  "CWE-134": "Use of Externally-Controlled Format String"
  "CWE-176": "Improper Handling of Unicode Encoding"
  "CWE-184": "Incomplete List of Disallowed Inputs"
  "CWE-190": "Integer Overflow or Wraparound"
  "CWE-208": "Observable Timing Discrepancy"
  "CWE-215": "Information Exposure Through Debug Information"
  "CWE-250": "Execution with Unnecessary Privileges"
  "CWE-284": "Improper Access Control"
  "CWE-311": "Missing Encryption of Sensitive Data"
  "CWE-312": "Cleartext Storage of Sensitive Information"
  "CWE-346": "Origin Validation Error"
  "CWE-400": "Uncontrolled Resource Consumption"
  "CWE-426": "Untrusted Search Path"
  "CWE-434": "Unrestricted Upload of File with Dangerous Type"
  "CWE-451": "User Interface (UI) Misrepresentation of Critical Information"
  "CWE-476": "NULL Pointer Dereference"
  "CWE-489": "Active Debug Code (OWASP A05:2021)"
  "CWE-532": "Insertion of Sensitive Information into Log File"
  "CWE-601": "URL Redirection to Untrusted Site"
  "CWE-643": "Improper Neutralization of Data within XPath Expressions"
  "CWE-776": "XML Entity Expansion"
  "CWE-943": "Improper Neutralization of Special Elements in Data Query Logic"
